# 使用官方的 Python 3.12.3 Slim 作為基礎映像
FROM python:3.12.3-slim

# 設定工作目錄為 /app
WORKDIR /app

# 將當前目錄的內容複製到容器中的 /app
COPY . /app

# 安裝 requirements.txt 中的必要套件
RUN pip install --no-cache-dir -r requirements.txt

# 暴露應用程式運行的埠
EXPOSE 5001

# 複製 entrypoint 腳本
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# 設定環境變數
ENV NAME World

# 當容器啟動時運行 entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
